# Copyright 2020 Cloudbase Solutions Srl
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#
# Module manifest for module 'WindowsImageConfig'
#
# Generated by: Adrian Vladu
#
# Generated on: 1/21/2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Config.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '3629ce90-b0dd-45b8-846a-389e5acad1e1'

# Author of this module
Author = 'Adrian Vladu'

# Company or vendor of this module
CompanyName = 'Cloudbase Solutions SRL'

# Copyright statement for this module
Copyright = '(c) 2020 Cloudbase Solutions SRL. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Powershell module to create / read Windows Image configuration files.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'


# Functions to export from this module
FunctionsToExport = @("Get-WindowsImageConfig", "New-WindowsImageConfig")

AliasesToExport = ""
}

